# Generated by Django 3.1 on 2022-03-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название банка')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('contract_number', models.CharField(max_length=200, verbose_name='Номер договора')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('price', models.FloatField(verbose_name='Стоимость проекта')),
                ('additional_pay', models.FloatField(blank=True, null=True, verbose_name='Дополнительная оплата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='contract.customer')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='номер счета')),
                ('price', models.FloatField(verbose_name='Стоимость счета')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='contract.bank')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='contract.project')),
            ],
            options={
                'ordering': ['-bank', '-number'],
            },
        ),
    ]
