# Generated by Django 3.1 on 2022-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_pay',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Дополнительная оплата'),
        ),
    ]
