# Generated by Django 3.1 on 2022-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20220421_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additional_pay',
            field=models.FloatField(default=0, verbose_name='Дополнительная оплата'),
        ),
    ]
