# Generated by Django 3.1 on 2022-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20220424_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bik',
            field=models.CharField(default='default', max_length=200, verbose_name='Бик банка'),
        ),
        migrations.AddField(
            model_name='bank',
            name='correspondent_account',
            field=models.CharField(default='default', max_length=200, verbose_name='Кор. счет'),
        ),
        migrations.AddField(
            model_name='bank',
            name='payment_account',
            field=models.CharField(default='default', max_length=200, verbose_name='Расч. счет'),
        ),
        migrations.AddField(
            model_name='check',
            name='create_date',
            field=models.CharField(default='default', max_length=200, verbose_name='дата чека'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='default', max_length=200, verbose_name='название банка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='предмет договора'),
        ),
    ]
