# Generated by Django 3.1 on 2022-04-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20220424_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
