# Generated by Django 3.1 on 2022-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_bank_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_project',
            field=models.CharField(default='default', max_length=200, verbose_name='Дата договора'),
        ),
    ]
